In [1]:
import torch
from transformers import PerceiverTokenizer

In [2]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [3]:
version = "deepmind/language-perceiver"
sequence = "The quick brown fox jumps over the lazy dog."
max_length = 20

# PerceiverTokenizer

In [4]:
tokenizer: PerceiverTokenizer = PerceiverTokenizer.from_pretrained(version)
tokenizer

Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.
Using unk_token, but it is not set yet.


PerceiverTokenizer(name_or_path='deepmind/language-perceiver', vocab_size=262, model_max_length=2048, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': AddedToken("[BOS]", rstrip=False, lstrip=False, single_word=False, normalized=True), 'eos_token': AddedToken("[EOS]", rstrip=False, lstrip=False, single_word=False, normalized=True), 'sep_token': AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=True), 'pad_token': AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=True), 'cls_token': AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=True), 'mask_token': AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=True)}, clean_up_tokenization_spaces=True)

## special ids and tokens

In [5]:
print(tokenizer.all_special_ids)
print(tokenizer.all_special_tokens)

[1, 2, 5, 0, 4, 3]
['[BOS]', '[EOS]', '[SEP]', '[PAD]', '[CLS]', '[MASK]']


## tokenize(sequence)

In [10]:
tokens = tokenizer.tokenize(sequence)
tokens

['T',
 'h',
 'e',
 ' ',
 'q',
 'u',
 'i',
 'c',
 'k',
 ' ',
 'b',
 'r',
 'o',
 'w',
 'n',
 ' ',
 'f',
 'o',
 'x',
 ' ',
 'j',
 'u',
 'm',
 'p',
 's',
 ' ',
 'o',
 'v',
 'e',
 'r',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'l',
 'a',
 'z',
 'y',
 ' ',
 'd',
 'o',
 'g',
 '.']

## convert_tokens_to_ids 将分词后的token映射为数字

In [11]:
ids = tokenizer.convert_tokens_to_ids(tokens)
ids

[90,
 110,
 107,
 38,
 119,
 123,
 111,
 105,
 113,
 38,
 104,
 120,
 117,
 125,
 116,
 38,
 108,
 117,
 126,
 38,
 112,
 123,
 115,
 118,
 121,
 38,
 117,
 124,
 107,
 120,
 38,
 122,
 110,
 107,
 38,
 114,
 103,
 128,
 127,
 38,
 106,
 117,
 109,
 52]

## encode = tokenize + convert_tokens_to_ids

In [12]:
print(tokenizer.encode(sequence, add_special_tokens=False))
ids = tokenizer.encode(sequence, add_special_tokens=True)
ids

[90, 110, 107, 38, 119, 123, 111, 105, 113, 38, 104, 120, 117, 125, 116, 38, 108, 117, 126, 38, 112, 123, 115, 118, 121, 38, 117, 124, 107, 120, 38, 122, 110, 107, 38, 114, 103, 128, 127, 38, 106, 117, 109, 52]


[4,
 90,
 110,
 107,
 38,
 119,
 123,
 111,
 105,
 113,
 38,
 104,
 120,
 117,
 125,
 116,
 38,
 108,
 117,
 126,
 38,
 112,
 123,
 115,
 118,
 121,
 38,
 117,
 124,
 107,
 120,
 38,
 122,
 110,
 107,
 38,
 114,
 103,
 128,
 127,
 38,
 106,
 117,
 109,
 52,
 5]

In [13]:
# encode前后代表开始和结束
tokenizer.convert_ids_to_tokens([4, 5])

['[CLS]', '[SEP]']

## batch_encode_plus = batch encode

In [14]:
tokenizer.batch_encode_plus([sequence], add_special_tokens=True, padding=True)

{'input_ids': [[4, 90, 110, 107, 38, 119, 123, 111, 105, 113, 38, 104, 120, 117, 125, 116, 38, 108, 117, 126, 38, 112, 123, 115, 118, 121, 38, 117, 124, 107, 120, 38, 122, 110, 107, 38, 114, 103, 128, 127, 38, 106, 117, 109, 52, 5]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}

## convert_ids_to_tokens 将数字映射为token

In [15]:
print(tokenizer.convert_ids_to_tokens(ids))
tokens = tokenizer.convert_ids_to_tokens(ids, skip_special_tokens=True)
tokens

['[CLS]', 'T', 'h', 'e', ' ', 'q', 'u', 'i', 'c', 'k', ' ', 'b', 'r', 'o', 'w', 'n', ' ', 'f', 'o', 'x', ' ', 'j', 'u', 'm', 'p', 's', ' ', 'o', 'v', 'e', 'r', ' ', 't', 'h', 'e', ' ', 'l', 'a', 'z', 'y', ' ', 'd', 'o', 'g', '.', '[SEP]']


['T',
 'h',
 'e',
 ' ',
 'q',
 'u',
 'i',
 'c',
 'k',
 ' ',
 'b',
 'r',
 'o',
 'w',
 'n',
 ' ',
 'f',
 'o',
 'x',
 ' ',
 'j',
 'u',
 'm',
 'p',
 's',
 ' ',
 'o',
 'v',
 'e',
 'r',
 ' ',
 't',
 'h',
 'e',
 ' ',
 'l',
 'a',
 'z',
 'y',
 ' ',
 'd',
 'o',
 'g',
 '.']

## convert_tokens_to_string 将token转换为string

In [16]:
tokenizer.convert_tokens_to_string(tokens)

'The quick brown fox jumps over the lazy dog.'

## decode = convert_ids_to_tokens + convert_tokens_to_string

In [17]:
print(tokenizer.decode(ids))
print(tokenizer.decode(ids, skip_special_tokens=True))

[CLS]The quick brown fox jumps over the lazy dog.[SEP]
The quick brown fox jumps over the lazy dog.


## batch_decode = batch decode

In [18]:
print(tokenizer.batch_decode([ids]))
print(tokenizer.batch_decode([ids], skip_special_tokens=True))

['[CLS]The quick brown fox jumps over the lazy dog.[SEP]']
['The quick brown fox jumps over the lazy dog.']


## tokenizer([sequence])

In [19]:
inputs = tokenizer(
    sequence,                           # 单个句子
    truncation = True,                  # 超出max_length截断处理
    padding = "max_length",             # 填充方式选择 [True, 'longest', 'max_length', 'do_not_pad']
    # max_length = max_length,          # 最长长度,不设置默认为模型最大长度
    add_special_tokens = True,          # text添加特殊key
    return_length = True,               # 返回有效长度
    return_overflowing_tokens = False,  # 返回所有的文本片段（由于文本比较长，默认情况下超过预设截断长度的token会被丢失。如果设置了return_overflowing_tokens=True则会返回所有的token片段）。
    return_tensors = "pt"               # 返回数据格式 np pt tf jax
).to(device)

print(inputs.keys())
print(inputs["input_ids"])      # 对应文字id
print(inputs["attention_mask"]) # 对应是否是文字
print(inputs["length"])         # 对应总长度长度

dict_keys(['input_ids', 'attention_mask', 'length'])


tensor([[  4,  90, 110,  ...,   0,   0,   0]], device='cuda:0')
tensor([[1, 1, 1,  ..., 0, 0, 0]], device='cuda:0')
tensor([2048], device='cuda:0')


In [20]:
inputs = tokenizer(
    [sequence] * 2,                     # 句子batch
    truncation = True,                  # 超出max_length截断处理
    padding = True,                     # 填充方式选择 [True, 'longest', 'max_length', 'do_not_pad']
    # max_length = max_length,          # 最长长度,不设置默认为模型最大长度
    add_special_tokens = True,          # text添加特殊key
    return_length = True,               # 返回有效长度
    return_overflowing_tokens = False,  # 返回所有的文本片段（由于文本比较长，默认情况下超过预设截断长度的token会被丢失。如果设置了return_overflowing_tokens=True则会返回所有的token片段）。
    return_tensors = "pt"               # 返回数据格式 np pt tf jax
).to(device)

print(inputs.keys())
print(inputs["input_ids"])      # 对应文字id 添加了['<|startoftext|>', '<|endoftext|>'],和encode相同
print(inputs["attention_mask"]) # 对应是否是文字
print(inputs["length"])         # 对应有效文字长度

dict_keys(['input_ids', 'length', 'attention_mask'])
tensor([[  4,  90, 110, 107,  38, 119, 123, 111, 105, 113,  38, 104, 120, 117,
         125, 116,  38, 108, 117, 126,  38, 112, 123, 115, 118, 121,  38, 117,
         124, 107, 120,  38, 122, 110, 107,  38, 114, 103, 128, 127,  38, 106,
         117, 109,  52,   5],
        [  4,  90, 110, 107,  38, 119, 123, 111, 105, 113,  38, 104, 120, 117,
         125, 116,  38, 108, 117, 126,  38, 112, 123, 115, 118, 121,  38, 117,
         124, 107, 120,  38, 122, 110, 107,  38, 114, 103, 128, 127,  38, 106,
         117, 109,  52,   5]], device='cuda:0')
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],
       device='cuda:0')
tensor([46, 46], device='cuda:0')
